version: '3'
services:
  jekyll:
    image: jekyll/jekyll
    ports:
      - "4000:4000"
    volumes:
      - ./:/srv/jekyll
      - vendor-bundle:/usr/local/bundle
    tty: true
    entrypoint: ["jekyll","serve","--incremental"]
    environment:
      JEKYLL_GITHUB_TOKEN: ${JEKYLL_GITHUB_TOKEN}
      FORCE_POLLING: 1
volumes:
  vendor-bundle:

